on:
    push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Display value
              run: echo "Actions ready"
            
            - name: Display more data
              run: echo "More values"
